import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./_components/providers/store.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> d66ae0edafb79fa333b3ee73540fcc3ad2af8d6e
    </html>
  );
}
